# Generated by Django 5.2.15 on 2026-07-27 00:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schema_version', models.CharField(default='0.1', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee_label', models.CharField(max_length=120)),
                ('scope', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.CharField(default='general', max_length=40)),
                ('text', models.CharField(max_length=200)),
                ('symbol', models.CharField(blank=True, default='', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pack', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=300)),
                ('source_type', models.CharField(default='text', max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('in_progress', 'In progress'), ('waiting_for_user', 'Waiting for you'), ('blocked', 'Blocked'), ('needs_support', 'Needs support'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=30)),
                ('source_text', models.TextField(blank=True, default='')),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('task_graph', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('retention_policy', models.CharField(default='delete_on_completion', max_length=30)),
                ('no_storage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('active_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accessprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('card_type', models.CharField(choices=[('summary', 'Summary'), ('instruction', 'Instruction'), ('information', 'Information'), ('checklist', 'Checklist'), ('choice', 'Choice'), ('warning', 'Warning'), ('communication', 'Communication'), ('confirmation', 'Confirmation'), ('recovery', 'Recovery'), ('completion', 'Completion')], max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.tasksession')),
            ],
            options={
                'ordering': ['session_id', 'sequence'],
                'unique_together': {('session', 'sequence')},
            },
        ),
    ]
